apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-skeleton
  labels:
    app: node-skeleton
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-skeleton
    spec:
      containers:
        - name: node-skeleton
          command: ["yarn", "prod"]
          image: gcr.io/gordion-2/lighthouse-runner:0138cbd77f994357a887766715ed7f0fc1107b61
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
