apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-skeleton
  labels:
    app: node-skeleton
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-skeleton
    spec:
      containers:
        - name: node-skeleton
          image: gcr.io/gordion-2/lighthouse-runner:5bf88fb36a5a48edd5af18a0f0a10aeae7b7fbed
