apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lighthouse-runner
  labels:
    app: lighthouse-runner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lighthouse-runner
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: lighthouse-runner-pubsub
      containers:
        - name: lighthouse-runner
          command: ["yarn", "prod"]
          image: gcr.io/gordion-project/lighthouse-runner:8492d4ad4b9b88a06c213a23f286dc354d98f387
          resources:
            requests:
              cpu: 200m
              memory: 3000Mi
            limits:
              cpu: 6000m
              memory: 6000Mi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: google-cloud-key
              mountPath: "/var/secrets/google"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"

---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse-runner
spec:
  type: LoadBalancer
  selector:
    app: lighthouse-runner
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
