apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lighthouse-runner
  labels:
    app: lighthouse-runner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lighthouse-runner
    spec:
      containers:
        - name: lighthouse-runner
          command: ["yarn", "prod"]
          image: gcr.io/gordion-project/lighthouse-runner:0585711b525649a49f7d0abaafd698be6810cdd2
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN

---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse-runner
spec:
  type: LoadBalancer
  selector:
    app: lighthouse-runner
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
